# Generated by Django 4.1.6 on 2023-03-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_disability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disability',
            field=models.CharField(choices=[('disable', 'disable'), ('non_disable', 'non-disable')], max_length=200),
        ),
    ]
