# Generated by Django 4.1.6 on 2023-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Departmnet',
            new_name='Department',
        ),
        migrations.AddField(
            model_name='user',
            name='collage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stream',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
