# Generated by Django 4.1.6 on 2023-02-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stream',
            field=models.CharField(choices=[('social', 'social'), ('natural', 'natural')], default=6, max_length=200),
            preserve_default=False,
        ),
    ]
