# Generated by Django 4.1.6 on 2023-02-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Student_or_Not',
        ),
    ]
