# Generated by Django 4.1.4 on 2023-01-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_phone_no_alter_useraccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='Role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.role'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
