# Generated by Django 4.1.4 on 2023-01-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_useraccount_role_alter_useraccount_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FirstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='LastName',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(default=234, unique=True),
            preserve_default=False,
        ),
    ]
