# Generated by Django 4.1.4 on 2023-01-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_studentbulkupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentBulkUpload',
        ),
    ]
