# Generated by Django 4.1.4 on 2023-02-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_delete_studentbulkupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Id_no',
            field=models.CharField(max_length=200),
        ),
    ]
