# Generated by Django 4.1.6 on 2023-03-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Block_name', models.CharField(max_length=100)),
                ('Block_type', models.CharField(choices=[('Main Campus', 'Main Campus'), ('Clustor Campus', 'Clustor Campus'), ('Health Campus', 'Health Campus'), ('Butajera Campus', 'Butajera Campus')], max_length=150)),
                ('Block_purpose', models.CharField(choices=[('Males Block', 'Males Block'), ('Females Block', 'Females Block')], max_length=100)),
                ('Block_Capacity', models.IntegerField()),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stud_id', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('collage', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dorm_name', models.CharField(max_length=100)),
                ('Capacity', models.CharField(max_length=10)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=150)),
                ('Block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.block')),
            ],
        ),
    ]
