# Generated by Django 4.1.6 on 2023-02-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Block_name', models.CharField(max_length=100)),
                ('Block_type', models.CharField(choices=[('Single-Block', 'Single Block'), ('4-Sieded-Block', '4_Sided Block')], max_length=150)),
                ('Block_purpose', models.CharField(choices=[('Males Block', 'Males Block'), ('Females Block', 'Females Block')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dorm_name', models.CharField(max_length=100)),
                ('Capacity', models.CharField(max_length=10)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=150)),
                ('Block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.block')),
            ],
        ),
    ]
