# Generated by Django 4.1.6 on 2023-02-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stud_id', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
            ],
        ),
    ]
