# Generated by Django 4.1.6 on 2023-02-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDean', '0002_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='collage',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placement',
            name='department',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
