# Generated by Django 4.1.6 on 2023-03-07 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StudentDean', '0002_alter_placement_block_alter_placement_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='collage',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='department',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='stream',
        ),
        migrations.AlterField(
            model_name='placement',
            name='Stud_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
