# Generated by Django 4.1.4 on 2023-01-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDean', '0003_alter_dorm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=150),
        ),
    ]
