# Generated by Django 4.1.6 on 2023-02-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDean', '0003_placement_collage_placement_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=4, max_length=100),
            preserve_default=False,
        ),
    ]
