# Generated by Django 4.1.6 on 2023-02-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDean', '0005_block_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='batch',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
